// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.2
// source: seqdb.proto

package cloudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RangeOption int32

const (
	RangeOption_WithBoth     RangeOption = 0
	RangeOption_WithoutStart RangeOption = 1
	RangeOption_WithoutEnd   RangeOption = 2
	RangeOption_WithoutBoth  RangeOption = 3
)

// Enum value maps for RangeOption.
var (
	RangeOption_name = map[int32]string{
		0: "WithBoth",
		1: "WithoutStart",
		2: "WithoutEnd",
		3: "WithoutBoth",
	}
	RangeOption_value = map[string]int32{
		"WithBoth":     0,
		"WithoutStart": 1,
		"WithoutEnd":   2,
		"WithoutBoth":  3,
	}
)

func (x RangeOption) Enum() *RangeOption {
	p := new(RangeOption)
	*p = x
	return p
}

func (x RangeOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeOption) Descriptor() protoreflect.EnumDescriptor {
	return file_seqdb_proto_enumTypes[0].Descriptor()
}

func (RangeOption) Type() protoreflect.EnumType {
	return &file_seqdb_proto_enumTypes[0]
}

func (x RangeOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeOption.Descriptor instead.
func (RangeOption) EnumDescriptor() ([]byte, []int) {
	return file_seqdb_proto_rawDescGZIP(), []int{0}
}

type SeqKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizId []byte `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	Seq   int32  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *SeqKey) Reset() {
	*x = SeqKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seqdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeqKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqKey) ProtoMessage() {}

func (x *SeqKey) ProtoReflect() protoreflect.Message {
	mi := &file_seqdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqKey.ProtoReflect.Descriptor instead.
func (*SeqKey) Descriptor() ([]byte, []int) {
	return file_seqdb_proto_rawDescGZIP(), []int{0}
}

func (x *SeqKey) GetBizId() []byte {
	if x != nil {
		return x.BizId
	}
	return nil
}

func (x *SeqKey) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SeqItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *SeqKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SeqItem) Reset() {
	*x = SeqItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seqdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeqItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqItem) ProtoMessage() {}

func (x *SeqItem) ProtoReflect() protoreflect.Message {
	mi := &file_seqdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqItem.ProtoReflect.Descriptor instead.
func (*SeqItem) Descriptor() ([]byte, []int) {
	return file_seqdb_proto_rawDescGZIP(), []int{1}
}

func (x *SeqItem) GetKey() *SeqKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SeqItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SeqItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*SeqItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SeqItems) Reset() {
	*x = SeqItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seqdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeqItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqItems) ProtoMessage() {}

func (x *SeqItems) ProtoReflect() protoreflect.Message {
	mi := &file_seqdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqItems.ProtoReflect.Descriptor instead.
func (*SeqItems) Descriptor() ([]byte, []int) {
	return file_seqdb_proto_rawDescGZIP(), []int{2}
}

func (x *SeqItems) GetItems() []*SeqItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PutItemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutItemResp) Reset() {
	*x = PutItemResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seqdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutItemResp) ProtoMessage() {}

func (x *PutItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_seqdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutItemResp.ProtoReflect.Descriptor instead.
func (*PutItemResp) Descriptor() ([]byte, []int) {
	return file_seqdb_proto_rawDescGZIP(), []int{3}
}

type DelRangeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelRangeResp) Reset() {
	*x = DelRangeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seqdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRangeResp) ProtoMessage() {}

func (x *DelRangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_seqdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRangeResp.ProtoReflect.Descriptor instead.
func (*DelRangeResp) Descriptor() ([]byte, []int) {
	return file_seqdb_proto_rawDescGZIP(), []int{4}
}

type RangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start   *SeqKey     `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End     *SeqKey     `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Reverse bool        `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"`                        // 默认 [start -> end], true 时 [end -> start] 受 limit 约束
	Option  RangeOption `protobuf:"varint,4,opt,name=option,proto3,enum=cloudpb.RangeOption" json:"option,omitempty"` // 默认闭区间，可选择去除左右区间
}

func (x *RangeReq) Reset() {
	*x = RangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seqdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeReq) ProtoMessage() {}

func (x *RangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_seqdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeReq.ProtoReflect.Descriptor instead.
func (*RangeReq) Descriptor() ([]byte, []int) {
	return file_seqdb_proto_rawDescGZIP(), []int{5}
}

func (x *RangeReq) GetStart() *SeqKey {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RangeReq) GetEnd() *SeqKey {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *RangeReq) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

func (x *RangeReq) GetOption() RangeOption {
	if x != nil {
		return x.Option
	}
	return RangeOption_WithBoth
}

var File_seqdb_proto protoreflect.FileDescriptor

var file_seqdb_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x65, 0x71, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x22, 0x31, 0x0a, 0x06, 0x53, 0x65, 0x71, 0x4b, 0x65, 0x79,
	0x12, 0x15, 0x0a, 0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x62, 0x69, 0x7a, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x42, 0x0a, 0x07, 0x53, 0x65, 0x71,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x21, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x4b,
	0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a,
	0x08, 0x53, 0x65, 0x71, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x9c, 0x01, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x4b, 0x65, 0x79, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x4b,
	0x65, 0x79, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2a,
	0x4e, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c,
	0x0a, 0x08, 0x57, 0x69, 0x74, 0x68, 0x42, 0x6f, 0x74, 0x68, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x45, 0x6e, 0x64, 0x10, 0x02, 0x12, 0x0f,
	0x0a, 0x0b, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x42, 0x6f, 0x74, 0x68, 0x10, 0x03, 0x32,
	0xfd, 0x01, 0x0a, 0x05, 0x53, 0x65, 0x71, 0x44, 0x62, 0x12, 0x2e, 0x0a, 0x03, 0x50, 0x75, 0x74,
	0x12, 0x11, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x50, 0x75,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x4b, 0x65,
	0x79, 0x1a, 0x10, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x2d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x4b, 0x65, 0x79,
	0x12, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x4b, 0x65,
	0x79, 0x1a, 0x0f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x71, 0x4b,
	0x65, 0x79, 0x12, 0x32, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x11, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x71, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x11, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x2e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x0a, 0x5a, 0x08, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_seqdb_proto_rawDescOnce sync.Once
	file_seqdb_proto_rawDescData = file_seqdb_proto_rawDesc
)

func file_seqdb_proto_rawDescGZIP() []byte {
	file_seqdb_proto_rawDescOnce.Do(func() {
		file_seqdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_seqdb_proto_rawDescData)
	})
	return file_seqdb_proto_rawDescData
}

var file_seqdb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seqdb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_seqdb_proto_goTypes = []interface{}{
	(RangeOption)(0),     // 0: cloudpb.RangeOption
	(*SeqKey)(nil),       // 1: cloudpb.SeqKey
	(*SeqItem)(nil),      // 2: cloudpb.SeqItem
	(*SeqItems)(nil),     // 3: cloudpb.SeqItems
	(*PutItemResp)(nil),  // 4: cloudpb.PutItemResp
	(*DelRangeResp)(nil), // 5: cloudpb.DelRangeResp
	(*RangeReq)(nil),     // 6: cloudpb.RangeReq
}
var file_seqdb_proto_depIdxs = []int32{
	1,  // 0: cloudpb.SeqItem.key:type_name -> cloudpb.SeqKey
	2,  // 1: cloudpb.SeqItems.items:type_name -> cloudpb.SeqItem
	1,  // 2: cloudpb.RangeReq.start:type_name -> cloudpb.SeqKey
	1,  // 3: cloudpb.RangeReq.end:type_name -> cloudpb.SeqKey
	0,  // 4: cloudpb.RangeReq.option:type_name -> cloudpb.RangeOption
	3,  // 5: cloudpb.SeqDb.Put:input_type -> cloudpb.SeqItems
	1,  // 6: cloudpb.SeqDb.Get:input_type -> cloudpb.SeqKey
	1,  // 7: cloudpb.SeqDb.GetMaxKey:input_type -> cloudpb.SeqKey
	6,  // 8: cloudpb.SeqDb.QueryRange:input_type -> cloudpb.RangeReq
	6,  // 9: cloudpb.SeqDb.DeleteRange:input_type -> cloudpb.RangeReq
	4,  // 10: cloudpb.SeqDb.Put:output_type -> cloudpb.PutItemResp
	2,  // 11: cloudpb.SeqDb.Get:output_type -> cloudpb.SeqItem
	1,  // 12: cloudpb.SeqDb.GetMaxKey:output_type -> cloudpb.SeqKey
	3,  // 13: cloudpb.SeqDb.QueryRange:output_type -> cloudpb.SeqItems
	5,  // 14: cloudpb.SeqDb.DeleteRange:output_type -> cloudpb.DelRangeResp
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_seqdb_proto_init() }
func file_seqdb_proto_init() {
	if File_seqdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seqdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeqKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seqdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeqItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seqdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeqItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seqdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutItemResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seqdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRangeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seqdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seqdb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seqdb_proto_goTypes,
		DependencyIndexes: file_seqdb_proto_depIdxs,
		EnumInfos:         file_seqdb_proto_enumTypes,
		MessageInfos:      file_seqdb_proto_msgTypes,
	}.Build()
	File_seqdb_proto = out.File
	file_seqdb_proto_rawDesc = nil
	file_seqdb_proto_goTypes = nil
	file_seqdb_proto_depIdxs = nil
}
